In [ ]:
import numpy as np
# Numpy Advance V2:
# we can collapse the matrix in one dimension
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,4,(3,3))
print("real array \n",arr1)
print("real array\n",arr2)
print("converted array 1:",arr1.flatten())
print("converted array 2:",arr2.flatten())

real array 
 [[1 2 2]
 [3 3 1]
 [3 2 2]]
real array
 [[1 3 3]
 [1 2 1]
 [2 1 3]]
converted array 1: [1 2 2 3 3 1 3 2 2]
converted array 2: [1 3 3 1 2 1 2 1 3]


In [14]:
# expand the dimension of the array
import numpy as np
arr1=np.array([3,3,52,4,24,3])
print(arr1)
print(arr1.ndim)
# to expand the dimension
print("converted array on x axis \n",np.expand_dims(arr1,axis =0))# axis =0 : row wise or x axis
# to expand on y axis
print("converted array on y axis \n",np.expand_dims(arr1,axis=1))


[ 3  3 52  4 24  3]
1
converted array on x axis 
 [[ 3  3 52  4 24  3]]
converted array on y axis 
 [[ 3]
 [ 3]
 [52]
 [ 4]
 [24]
 [ 3]]
