In [ ]:
import numpy as np
# Numpy Advance V2:
# we can collapse the matrix in one dimension
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,4,(3,3))
print("real array \n",arr1)
print("real array\n",arr2)
print("converted array 1:",arr1.flatten())
print("converted array 2:",arr2.flatten())

real array 
 [[1 2 2]
 [3 3 1]
 [3 2 2]]
real array
 [[1 3 3]
 [1 2 1]
 [2 1 3]]
converted array 1: [1 2 2 3 3 1 3 2 2]
converted array 2: [1 3 3 1 2 1 2 1 3]


In [ ]:
# expand the dimension of the array
# expand_dims increases the dimension by 1
import numpy as np
arr1=np.array([3,3,52,4,24,3])
print(arr1)
print(arr1.ndim)
# to expand the dimension
print("converted array on x axis \n",np.expand_dims(arr1,axis =0))# axis =0 : row wise or x axis
# to expand on y axis
print("converted array on y axis \n",np.expand_dims(arr1,axis=1))


[ 3  3 52  4 24  3]
1
converted array on x axis 
 [[ 3  3 52  4 24  3]]
converted array on y axis 
 [[ 3]
 [ 3]
 [52]
 [ 4]
 [24]
 [ 3]]


In [17]:
""" queeze dimension : Dimension is size 1	Removes it
Dimension is size > 1	Keeps it
No dimension is size 1	No change """
arr=np.random.randint(1,4,(1,4))
print(arr.ndim)
arr=np.squeeze(arr)
print(arr.ndim)

2
1


In [21]:
# repeat the values of the matrix
arr=np.random.randint(1,4,(3,4))
print(" original array \n",arr)
print("---------------------- breaking the line -----------------------")
print(np.repeat(arr,3,axis=0)) # repeats the value 3 times row wise
print("---------------------- breaking the line -----------------------")
print(np.repeat(arr,3,axis=0)) # repeats the value 3 times column wise

 original array 
 [[1 1 1 3]
 [2 1 3 3]
 [3 1 1 3]]
---------------------- breaking the line -----------------------
[[1 1 1 3]
 [1 1 1 3]
 [1 1 1 3]
 [2 1 3 3]
 [2 1 3 3]
 [2 1 3 3]
 [3 1 1 3]
 [3 1 1 3]
 [3 1 1 3]]
---------------------- breaking the line -----------------------
[[1 1 1 3]
 [1 1 1 3]
 [1 1 1 3]
 [2 1 3 3]
 [2 1 3 3]
 [2 1 3 3]
 [3 1 1 3]
 [3 1 1 3]
 [3 1 1 3]]


In [24]:
# roll : shift the value according to given value
arr=np.random.randint(1,4,(3,4))
print(arr)
print(np.roll(arr,-1)) # column one is placed at last and second became first
print(np.roll(arr,-2))

[[2 1 2 2]
 [1 3 1 2]
 [3 2 1 1]]
[[1 2 2 1]
 [3 1 2 3]
 [2 1 1 2]]
[[2 2 1 3]
 [1 2 3 2]
 [1 1 2 1]]


In [14]:
import numpy as np
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,4,(3,3))
print("array 1\n",arr1)
print("array 2\n",arr2)
print("---------------------- breaking the line -----------------------")
# some operation that you can perform using numpy
print("index wise multiplication \n",np.multiply(arr1,arr2))
# some mathematical operation like
print("mean of the arr \n",np.mean(arr1))
print("standar deviation \n",np.std(arr1))
print("---------------------- breaking the line -----------------------")
print("maximum value of the array \n",np.max(arr1))
print("square of the matrix \n",np.square(arr1))
print("any power \n",np.pow(arr1,3))

array 1
 [[2 2 2]
 [3 2 2]
 [1 2 1]]
array 2
 [[2 3 1]
 [3 2 3]
 [1 1 3]]
---------------------- breaking the line -----------------------
index wise multiplication 
 [[4 6 2]
 [9 4 6]
 [1 2 3]]
mean of the arr 
 1.8888888888888888
standar deviation 
 0.5665577237325317
---------------------- breaking the line -----------------------
maximum value of the array 
 3
square of the matrix 
 [[4 4 4]
 [9 4 4]
 [1 4 1]]
any power 
 [[ 8  8  8]
 [27  8  8]
 [ 1  8  1]]


In [12]:
# sorting and searching in numpy array
import numpy as np
arr=np.random.randint(1,9,8) #creating a random array of length 8 range of num 1 to 9
print(arr)
print(arr.ndim)
""" to sort this arrray"""
print("sorting the array :",np.sort(arr))

[3 5 1 2 1 5 3 8]
1
sorting the array : [1 1 2 3 3 5 5 8]


In [30]:
sample_array=np.array([3,35,24,6,78,3,6,47,4362,4873,74747,7445,1,3])
# to search the element
""" searchsorted: it is used to find out the index where we can put the value"""
sorted_array=np.sort(sample_array)
print(sorted_array)
index =np.searchsorted(sorted_array,87)
print(index)
print("count the non zero element: ",np.count_nonzero(sorted_array))


[    1     3     3     3     6     6    24    35    47    78  4362  4873
  7445 74747]
10
count the non zero element:  14


In [1]:
# Slow way
import numpy as np
result = [x**2 for x in range(10000)]

# Fast way
arr = np.arange(10000)
result = arr ** 2


In [2]:
from numpy import ma
arr = np.array([1, 2, -99, 4])
masked_arr = ma.masked_equal(arr, -99)
print(masked_arr.mean())


2.3333333333333335
