# PCA : Principle Component analysis 

PCA is an unsupervised machine learning algorithm (or technique) used for dimensionality reduction.
It reduces the number of features while preserving as much variance as possible.
It is mainly used as a preprocessing step before training ML models.

Benefit: Faster training, less memory usage, reduced overfitting, and easier visualization.
Used for: High-dimensional datasets, image processing, preprocessing before ML models, and data visualization.

# curse of dimensionality:

After a certain point, adding more features provides little or no improvement in model performance,
while increasing training time, memory usage, and the risk of overfitting.

# feature selection and extraction technique:

Principal Components are new features created by combining the original features.

In [17]:
# Rituals
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [20]:
data=load_iris()
x=data.data
y=data.target
display(x)
display(x.shape)
display(y.shape)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
display(x_train)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

(150, 4)

(150,)

array([[-1.01827123,  1.2864604 , -1.39338902, -1.3621769 ],
       [-0.7730102 ,  2.43545215, -1.33550342, -1.49647603],
       [-0.03722712, -0.78172474,  0.74837808,  0.92090833],
       [ 0.20803391,  0.8268637 ,  0.4010645 ,  0.51801093],
       [ 1.06644751,  0.13746866,  0.51683569,  0.3837118 ],
       [-0.52774918,  1.97585545, -1.45127462, -1.09357864],
       [-0.52774918,  1.51625875, -1.33550342, -1.3621769 ],
       [-0.40511866, -1.47111979, -0.06202028, -0.28778385],
       [ 0.57592545, -0.55192639,  0.74837808,  0.3837118 ],
       [ 0.69855596,  0.13746866,  0.97992047,  0.7866092 ],
       [ 0.94381699, -0.09232969,  0.3431789 ,  0.24941267],
       [ 1.67960008,  1.2864604 ,  1.32723405,  1.72670311],
       [-0.15985763, -0.32212804,  0.2274077 ,  0.11511354],
       [ 2.17012213, -0.09232969,  1.61666204,  1.18950659],
       [-0.28248815, -0.09232969,  0.4010645 ,  0.3837118 ],
       [-0.89564072,  1.05666205, -1.39338902, -1.3621769 ],
       [ 2.29275265, -0.

In [22]:
pca=PCA(n_components=3)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)
display(x_train)
display(pca.explained_variance_ratio_)

array([[-2.43856330e+00,  7.35586144e-01, -7.81588331e-03],
       [-2.63428337e+00,  1.88627105e+00, -4.19501237e-02],
       [ 1.13420182e+00, -6.85306552e-01, -5.13628894e-01],
       [ 4.35677214e-01,  8.74249807e-01, -4.38805138e-01],
       [ 1.04487840e+00,  5.45555514e-01,  4.21914006e-01],
       [-2.23232240e+00,  1.56919349e+00,  1.05922124e-02],
       [-2.20450972e+00,  1.13039470e+00,  2.80220233e-01],
       [-5.12443695e-02, -1.52980650e+00,  2.67282013e-01],
       [ 1.09309956e+00, -2.72787810e-01,  2.10337322e-01],
       [ 1.35301331e+00,  4.34850016e-01, -1.60014106e-01],
       [ 8.58948724e-01,  2.78518606e-01,  4.99383934e-01],
       [ 2.32225779e+00,  1.91379407e+00, -3.82472241e-01],
       [ 1.94095164e-01, -3.49794971e-01, -1.37687084e-01],
       [ 2.78085695e+00,  7.91197578e-01,  6.17642766e-01],
       [ 3.28143460e-01, -1.66496463e-01, -4.76812012e-01],
       [-2.31814954e+00,  5.67551658e-01,  1.38140456e-01],
       [ 2.91517705e+00,  4.03763698e-01

array([0.71948203, 0.23842247, 0.04209549])