In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
from sklearn.model_selection import GridSearchCV

In [9]:
x,y=make_classification(n_samples=1000,n_features=10,n_redundant=5,n_informative=5,n_classes=3,random_state=42)
# OVR : one vs rest
# solver=lbfgs-> It is an optimization algorithm . Used to minimize loss function efficiently
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
classifier=LogisticRegression(multi_class='ovr',solver='lbfgs')
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print("Printing the Evaluation metrics: ......................")
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Printing the Evaluation metrics: ......................
[[71  7 10]
 [10 60 11]
 [16 22 43]]
0.696
              precision    recall  f1-score   support

           0       0.73      0.81      0.77        88
           1       0.67      0.74      0.71        81
           2       0.67      0.53      0.59        81

    accuracy                           0.70       250
   macro avg       0.69      0.69      0.69       250
weighted avg       0.69      0.70      0.69       250

